### ISSUE TITLE
Exclude repositories from Featured Projects

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/aoepeople.github.io#21]
We have repositories which are automatically used and often kept up to date, such as AOEpeople/_preview-opensource.
There is no need to show these repositories, so we want some way to exclude them.

Possible usage: have a list of excluded repos, fetch 6+len(list) and filter out repos and display up to 6.

**Comment by resah** [comment]
Was implemented in https://github.com/AOEpeople/aoepeople.github.io/pull/42 and can be configured in `config.toml` to exclude further repositories.
