### ISSUE TITLE
Extend RSS Feed

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/aoepeople.github.io#48]
Extend the feed to provide more data such as
- Tags
- Authors
- Preview-Image

**Comment by bastianccm** [comment]
https://gohugo.io/templates/rss/

**Comment by resah** [comment]
In accordance to https://www.rssboard.org/rss-specification I suggest the following tags instead: 
* a single `author` (we support a single author at the moment afaik)
* a list of `category` (for each tag)
* a `enclosure` for the preview image (don't know how to calculate the image size for the `length` attribute in Hugo)

**Comment by bastianccm** [comment]
🙇
